### ISSUE TITLE
Python Installation Error Message

### ISSUE THREAD

**Issue by hamiltoncj** [javaftw/inkscape2symbol#1]
I am getting the following error message when trying to install this on Windows using QGIS 3.8.3.

ModuleNotFoundError: No module named 'inkscape2symbol-master.resources' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/cjhamil/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inkscape2symbol-master\__init__.py", line 35, in classFactory
    from .inkscape2symbol import Inkscape2Symbol
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/cjhamil/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inkscape2symbol-master\inkscape2symbol.py", line 29, in 
    from .resources import *
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'inkscape2symbol-master.resources'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.3-Zanzibar Zanzibar, 685d8b15d2

**Comment by ygorigor** [comment]
Same issue

**Comment by javaftw** [comment]
Thanks, having a look at the issue now, hope to have it resolved soon

**Comment by klakar** [comment]
The resources.py file is missing in the package.
To fix temporarily just download it from the repository and save it in the plug-in folder.

**Comment by Bernd-Vogelgesang** [comment]
shouldn't there be the "-master"-part removed to avoid the mismatch between the plugin name and the file names? Saw this a lot in the past.

**Comment by javaftw** [comment]
> shouldn't there be the "-master"-part removed to avoid the mismatch between the plugin name and the file names? Saw this a lot in the past.

Yep, I noticed too late. I'll pay attention to that with the upcoming release
